/**
 * Review Extension Content Script V2
 * 评审标注浏览器扩展 - 内容脚本（架构重构版）
 *
 * @author dengqu
 * @version 2.7.0
 * @description 为 HTML 原型页面提供交互式评审标注功能
 *
 * 架构改进（v1 → v2）：
 * 1. 角标永不销毁，只切换 display 状态（解决角标消失后不恢复问题）
 * 2. 增强 selector：CSS.escape 转义 + 容错查找（解决部分页面定位失败）
 * 3. 全局统一滚动监听（捕获模式），覆盖所有嵌套滚动容器
 * 4. overlay 生命周期独立于评审模式，双向联动随时可用
 */

(function() {
  'use strict';

  const VERSION = '2.8.0';

  // ==================== 动效配置 ====================
  // 出场动效类型：'drop'（从天砸落）| 'flip'（卡片翻转）
  const PANEL_ENTRANCE_ANIMATION = 'flip';

  // ==================== 国际化 (i18n) ====================
  const userLang = navigator.language.startsWith('zh') ? 'zh' : 'en';

  const i18n = {
    zh: {
      // 版本信息
      loaded: '已加载',

      // 评审面板
      startReview: '开始评审',
      endReview: '结束评审',
      viewRecords: '评审记录',
      export: '导出',
      close: '关闭',
      dragHandle: '拖动',

      // 评论对话框
      addComment: '添加评论',
      commentContent: '评论内容',
      commentPlaceholder: '请输入评论内容...',
      type: '类型',
      priority: '优先级',
      cancel: '取消',
      save: '保存',

      // 评论类型
      typeIssue: '问题',
      typeSuggestion: '建议',
      typeDecision: '决策',
      typePending: '待确认',

      // 优先级
      p0: 'P0 - 必须修改',
      p1: 'P1 - 建议修改',
      p2: 'P2 - 可选优化',
      p0Short: 'P0',
      p1Short: 'P1',
      p2Short: 'P2',

      // 评论列表
      reviewRecords: '评审记录',
      noComments: '当前还没添加任何评审记录哦',
      guideTitle: '使用指南',
      guide1: '点击底部面板的「开始评审」进入评审模式',
      guide2: '鼠标移动到页面元素上，蓝色边框提示可标注区域',
      guide3: '点击目标元素，弹出评论框填写意见',
      guide4: '选择类型（问题/建议/决策/待确认）和优先级（P0~P2）',
      guide5: '保存后元素上出现红色编号角标',
      guide6: '评审完成后点击「导出」生成优化待办表',
      edit: '编辑',
      delete: '删除',

      // 导出对话框
      exportTitle: '导出评审文档',
      generating: '正在生成评审文档，请稍候...',
      downloadFile: '下载文件',
      copyToClipboard: '复制到剪贴板',

      // Markdown 生成
      untitledPage: '未命名页面',
      reviewRecordTitle: '原型评审记录',
      autoGenerated: '本文档由评审标注工具自动生成',
      basicInfo: '基本信息',
      pageTitle: '页面标题',
      reviewDate: '评审日期',
      totalComments: '评论总数',
      commentsCount: '条',
      reviewOpinions: '评审意见',
      p0Must: 'P0 — 必须修改',
      p1Should: 'P1 — 建议修改',
      p2Optional: 'P2 — 可选优化',
      noOpinions: '暂无评审意见。',
      savePath: '保存路径',
      usage: '使用方式',
      usageInstruction: '复制此文档内容，粘贴给 Claude 并说 "我已经完成了评审，请帮我保存评审记录"',

      // Toast 提示
      noCommentsToExport: '当前还没有任何评论，请先添加评论后再导出。',
      fileDownloaded: '文件已开始下载！',
      copiedToClipboard: '已复制到剪贴板！',
      pleaseEnterContent: '请输入评论内容',
      backupSaved: '评审数据已备份',
      backupRestored: '已从备份恢复评审数据',
      htmlExported: 'HTML 评审副本已下载',
      jsonBackupDone: 'JSON 备份已下载',
      syncSaved: '已同步到云端',
      syncFailed: '云端同步失败（数据已保存到本地）',
      dataRestoredFromHtml: '已从 HTML 注释中恢复评审数据',
      dataRestoredFromSync: '已从云端同步恢复评审数据',
      noBackupFound: '未找到可恢复的备份数据',
      backupMismatchTitle: '⚠ 备份来源不匹配',
      backupSource: '备份来源：',
      currentPage: '当前页面：',
      backupMismatchConfirm: '该备份可能不属于当前页面，仍然恢复吗？',
      confirmRestore: '仍然恢复',

      // 备份按钮
      backup: '备份',
      backupTitle: '数据备份',
      backupToJson: '导出 JSON 备份',
      backupToHtml: '导出 HTML 评审副本',
      restoreFromBackup: '从备份恢复',

      // 日志
      initialized: '已初始化',
      savedTo: '已保存到',
      loadedFrom: '已从',
      loadedComments: '加载',
      selectorFailed: 'selector 查找失败，尝试备用方案',
      backupFailed: '备用 selector 也失败'
    },
    en: {
      // Version info
      loaded: 'loaded',

      // Review panel
      startReview: 'Start Review',
      endReview: 'End Review',
      viewRecords: 'Review Records',
      export: 'Export',
      close: 'Close',
      dragHandle: 'Drag',

      // Comment dialog
      addComment: 'Add Comment',
      commentContent: 'Comment',
      commentPlaceholder: 'Enter your comment...',
      type: 'Type',
      priority: 'Priority',
      cancel: 'Cancel',
      save: 'Save',

      // Comment types
      typeIssue: 'Issue',
      typeSuggestion: 'Suggestion',
      typeDecision: 'Decision',
      typePending: 'Pending',

      // Priority
      p0: 'P0 - Must Fix',
      p1: 'P1 - Should Fix',
      p2: 'P2 - Optional',
      p0Short: 'P0',
      p1Short: 'P1',
      p2Short: 'P2',

      // Comment list
      reviewRecords: 'Review Records',
      noComments: 'No review records yet',
      guideTitle: 'Quick Guide',
      guide1: 'Click "Start Review" button at the bottom panel',
      guide2: 'Move mouse over page elements, blue border shows annotatable areas',
      guide3: 'Click target element to open comment dialog',
      guide4: 'Select type (Issue/Suggestion/Decision/Pending) and priority (P0~P2)',
      guide5: 'After saving, a red numbered badge appears on the element',
      guide6: 'Click "Export" when done to generate optimization checklist',
      edit: 'Edit',
      delete: 'Delete',

      // Export dialog
      exportTitle: 'Export Review Document',
      generating: 'Generating review document, please wait...',
      downloadFile: 'Download File',
      copyToClipboard: 'Copy to Clipboard',

      // Markdown generation
      untitledPage: 'Untitled Page',
      reviewRecordTitle: 'Prototype Review Record',
      autoGenerated: 'This document is auto-generated by the review annotation tool',
      basicInfo: 'Basic Information',
      pageTitle: 'Page Title',
      reviewDate: 'Review Date',
      totalComments: 'Total Comments',
      commentsCount: 'comments',
      reviewOpinions: 'Review Opinions',
      p0Must: 'P0 — Must Fix',
      p1Should: 'P1 — Should Fix',
      p2Optional: 'P2 — Optional',
      noOpinions: 'No review opinions.',
      savePath: 'Save Path',
      usage: 'Usage',
      usageInstruction: 'Copy this document and paste to Claude, then say "I have completed the review, please help me save the review record"',

      // Toast messages
      noCommentsToExport: 'No comments yet. Please add comments before exporting.',
      fileDownloaded: 'File download started!',
      copiedToClipboard: 'Copied to clipboard!',
      pleaseEnterContent: 'Please enter comment content',
      backupSaved: 'Review data backed up',
      backupRestored: 'Review data restored from backup',
      htmlExported: 'HTML review copy downloaded',
      jsonBackupDone: 'JSON backup downloaded',
      syncSaved: 'Synced to cloud',
      syncFailed: 'Cloud sync failed (data saved locally)',
      dataRestoredFromHtml: 'Review data restored from HTML comments',
      dataRestoredFromSync: 'Review data restored from cloud sync',
      noBackupFound: 'No backup data found',
      backupMismatchTitle: '⚠ Backup source mismatch',
      backupSource: 'Backup from: ',
      currentPage: 'Current page: ',
      backupMismatchConfirm: 'This backup may not belong to the current page. Restore anyway?',
      confirmRestore: 'Restore Anyway',

      // Backup buttons
      backup: 'Backup',
      backupTitle: 'Data Backup',
      backupToJson: 'Export JSON Backup',
      backupToHtml: 'Export HTML Review Copy',
      restoreFromBackup: 'Restore from Backup',

      // Logs
      initialized: 'initialized',
      savedTo: 'saved to',
      loadedFrom: 'loaded from',
      loadedComments: 'loaded',
      selectorFailed: 'selector lookup failed, trying fallback',
      backupFailed: 'fallback selector also failed'
    }
  };

  // 翻译函数
  function t(key) {
    return i18n[userLang][key] || i18n['en'][key] || key;
  }

  console.log(`[Review Extension V2] v${VERSION} ${t('loaded')}`);

  // ==================== 暗色模式检测 ====================
  /**
   * 检测页面是否为暗色模式
   * 综合检测：系统偏好 + 页面背景色 + 页面采样
   */
  function detectPageDarkMode() {
    // 1. 检查系统偏好
    const systemPrefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;

    // 2. 检查页面背景色
    const bodyBg = window.getComputedStyle(document.body).backgroundColor;
    const htmlBg = window.getComputedStyle(document.documentElement).backgroundColor;

    const bodyBrightness = calculateBrightness(bodyBg);
    const htmlBrightness = calculateBrightness(htmlBg);

    // 3. 采样页面主要区域的颜色
    const sampledBrightness = samplePageColors();

    // 综合判断：优先使用有效的背景色，如果都是透明则使用采样结果
    let avgBrightness = 255;
    let validSamples = 0;

    // 只有当背景色不是透明时才计入
    if (bodyBrightness < 255) {
      avgBrightness = bodyBrightness;
      validSamples++;
    }
    if (htmlBrightness < 255) {
      avgBrightness = validSamples > 0 ? (avgBrightness + htmlBrightness) / 2 : htmlBrightness;
      validSamples++;
    }

    // 如果 body 和 html 都是透明，采样结果权重更高
    if (validSamples === 0 && sampledBrightness < 255) {
      // 完全依赖采样结果
      console.log('[Review Extension] Using sampled brightness:', sampledBrightness);
      return sampledBrightness < 128;
    } else if (sampledBrightness < 255) {
      // 有背景色时，采样结果作为参考
      avgBrightness = validSamples > 0 ? (avgBrightness + sampledBrightness) / 2 : sampledBrightness;
      validSamples++;
    }

    // 如果有有效采样，使用采样结果；否则使用系统偏好
    const result = validSamples > 0 ? avgBrightness < 128 : systemPrefersDark;

    console.log('[Review Extension] Detection details:', {
      bodyBrightness,
      htmlBrightness,
      sampledBrightness,
      avgBrightness,
      validSamples,
      systemPrefersDark,
      result
    });

    return result;
  }

  /**
   * 采样页面主要区域的颜色
   */
  function samplePageColors() {
    // 增加更多采样点，覆盖页面不同区域
    const samplePoints = [
      { x: window.innerWidth * 0.5, y: window.innerHeight * 0.2 },
      { x: window.innerWidth * 0.5, y: window.innerHeight * 0.5 },
      { x: window.innerWidth * 0.5, y: window.innerHeight * 0.8 },
      { x: window.innerWidth * 0.2, y: window.innerHeight * 0.5 },
      { x: window.innerWidth * 0.8, y: window.innerHeight * 0.5 },
      { x: window.innerWidth * 0.3, y: window.innerHeight * 0.3 },
      { x: window.innerWidth * 0.7, y: window.innerHeight * 0.7 },
    ];

    let totalBrightness = 0;
    let validSamples = 0;

    samplePoints.forEach(point => {
      const element = document.elementFromPoint(point.x, point.y);
      if (element) {
        // 尝试获取元素的背景色，如果透明则向上查找父元素
        let currentElement = element;
        let attempts = 0;
        const maxAttempts = 10; // 最多向上查找10层

        while (currentElement && attempts < maxAttempts) {
          const bgColor = window.getComputedStyle(currentElement).backgroundColor;
          const brightness = calculateBrightness(bgColor);

          if (brightness < 255) {
            // 找到了有效的背景色
            totalBrightness += brightness;
            validSamples++;
            console.log(`[Review Extension] Sampled element at (${Math.round(point.x)}, ${Math.round(point.y)}):`, {
              element: currentElement.tagName,
              bgColor,
              brightness
            });
            break;
          }

          // 背景色是透明的，继续向上查找
          currentElement = currentElement.parentElement;
          attempts++;
        }
      }
    });

    const result = validSamples > 0 ? totalBrightness / validSamples : 255;
    console.log(`[Review Extension] Sampling complete: ${validSamples} valid samples, average brightness: ${result}`);
    return result;
  }

  /**
   * 计算颜色亮度（0-255）
   * 使用感知亮度公式
   */
  function calculateBrightness(color) {
    if (!color || color === 'transparent' || color === 'rgba(0, 0, 0, 0)') {
      return 255; // 默认为亮色
    }

    const rgb = color.match(/\d+/g);
    if (!rgb || rgb.length < 3) return 255;

    const [r, g, b] = rgb.map(Number);
    // 使用感知亮度公式
    return (r * 299 + g * 587 + b * 114) / 1000;
  }

  // ==================== 面板周边颜色检测与主题切换 ====================
  /**
   * 检测面板周边的颜色，判断应该使用亮色还是暗色主题
   * 使用 CSS 检测算法（不完美，但能覆盖大多数情况）
   * @returns {boolean} true = 使用亮色主题（周边是暗色），false = 使用暗色主题（周边是亮色）
   */
  function detectPanelSurroundingColor() {
    if (!reviewPanel) return false;

    const rect = reviewPanel.getBoundingClientRect();

    // 采样距离：平衡避开小元素和不超出目标区域
    const sampleDistance = 50;
    const samplePoints = [
      // 面板底部（3个点）
      { x: rect.left + rect.width * 0.25, y: rect.bottom + sampleDistance },
      { x: rect.left + rect.width * 0.5, y: rect.bottom + sampleDistance },
      { x: rect.left + rect.width * 0.75, y: rect.bottom + sampleDistance },

      // 面板顶部（3个点）
      { x: rect.left + rect.width * 0.25, y: rect.top - sampleDistance },
      { x: rect.left + rect.width * 0.5, y: rect.top - sampleDistance },
      { x: rect.left + rect.width * 0.75, y: rect.top - sampleDistance },

      // 面板左侧（3个点）
      { x: rect.left - sampleDistance, y: rect.top + rect.height * 0.25 },
      { x: rect.left - sampleDistance, y: rect.top + rect.height * 0.5 },
      { x: rect.left - sampleDistance, y: rect.top + rect.height * 0.75 },

      // 面板右侧（3个点）
      { x: rect.right + sampleDistance, y: rect.top + rect.height * 0.25 },
      { x: rect.right + sampleDistance, y: rect.top + rect.height * 0.5 },
      { x: rect.right + sampleDistance, y: rect.top + rect.height * 0.75 },
    ];

    let totalBrightness = 0;
    let validSamples = 0;
    const brightnessValues = [];

    samplePoints.forEach(point => {
      // 确保采样点在视口内
      if (point.x < 0 || point.x > window.innerWidth ||
          point.y < 0 || point.y > window.innerHeight) {
        return;
      }

      const element = document.elementFromPoint(point.x, point.y);
      if (!element || element === reviewPanel || reviewPanel.contains(element)) {
        return;
      }

      // 向上查找父元素，寻找有效的背景色
      let currentElement = element;
      let attempts = 0;
      let brightness = 255;
      let foundValidColor = false;

      while (currentElement && attempts < 6) {
        const computedStyle = window.getComputedStyle(currentElement);
        const bg = computedStyle.backgroundColor;
        const bgImage = computedStyle.backgroundImage;
        
        // 获取元素尺寸
        const elementRect = currentElement.getBoundingClientRect();
        const elementArea = elementRect.width * elementRect.height;

        brightness = calculateBrightness(bg);

        // 判断是否是有效的背景色
        if (brightness < 255) {
          if (bgImage && bgImage !== 'none') {
            // 有背景图片，假设是中等亮度（150）
            // 这样既不会太亮也不会太暗，让检测更保守
            brightness = 150;
            foundValidColor = true;
            break;
          } else if (elementArea > 1500) {
            // 元素面积足够大
            foundValidColor = true;
            break;
          }
        }

        currentElement = currentElement.parentElement;
        attempts++;
      }

      if (foundValidColor && brightness < 255) {
        brightnessValues.push(brightness);
        totalBrightness += brightness;
        validSamples++;
      }
    });

    // 如果没有有效采样，默认使用暗色主题（适合大多数亮色背景）
    if (validSamples === 0) {
      console.log('[Review Extension] No valid samples, using default dark theme');
      return false;
    }

    // 计算平均亮度
    const avgBrightness = totalBrightness / validSamples;

    // 计算中位数（更稳定，不容易被极端值影响）
    brightnessValues.sort((a, b) => a - b);
    const medianBrightness = brightnessValues[Math.floor(brightnessValues.length / 2)];

    // 使用中位数和平均值的加权平均（中位数权重更高）
    const finalBrightness = medianBrightness * 0.7 + avgBrightness * 0.3;
    const isDark = finalBrightness < 128;

    console.log('[Review Extension] Panel surrounding detection (CSS):', {
      avgBrightness: avgBrightness.toFixed(1),
      medianBrightness: medianBrightness.toFixed(1),
      finalBrightness: finalBrightness.toFixed(1),
      validSamples,
      isDark,
      shouldUseLightTheme: isDark,
      allValues: brightnessValues.map(v => v.toFixed(0)).join(', ')
    });

    return isDark;
  }



  /**
   * 应用主题到面板（带平滑过渡）
   * @param {boolean} useLightTheme - 是否使用亮色主题
   */
  function applyTheme(useLightTheme) {
    if (!reviewPanel) return;

    if (useLightTheme) {
      reviewPanel.classList.add('dq-light-theme');
      if (commentListPanel) {
        commentListPanel.classList.add('dq-light-theme');
      }
    } else {
      reviewPanel.classList.remove('dq-light-theme');
      if (commentListPanel) {
        commentListPanel.classList.remove('dq-light-theme');
      }
    }
  }

  /**
   * 检测并切换主题（带平滑过渡）
   */
  function detectAndSwitchTheme() {
    console.log('[Review Extension] detectAndSwitchTheme called');
    try {
      const shouldUseLightTheme = detectPanelSurroundingColor();
      console.log('[Review Extension] shouldUseLightTheme:', shouldUseLightTheme);
      applyTheme(shouldUseLightTheme);
    } catch (error) {
      console.error('[Review Extension] detectAndSwitchTheme error:', error);
    }
  }

  // ==================== 状态管理 ====================
  let isReviewMode = false;
  let isPanelVisible = false;
  let annotations = [];
  let currentAnnotationId = 0;
  let selectedElement = null;
  let commentDialog = null;
  let reviewPanel = null;
  let commentListPanel = null;
  let hoverOverlay = null;
  let selectOverlay = null;

  // 核心映射表
  const annotationMarkerMap = new Map();      // annotationId → { marker, element }
  const annotationElementMap = new Map();      // annotationId → element（运行时引用）

  // ESC 双击检测
  let lastEscTime = 0;
  const ESC_DOUBLE_CLICK_THRESHOLD = 500;

  // 拖动状态
  let isDragging = false;
  let dragStartX = 0;
  let dragStartY = 0;
  let panelStartX = 0;
  let panelStartY = 0;

  // 鼠标移动目标
  let hoveredElement = null;

  // iframe 支持
  let iframeListeners = []; // { iframe, doc, clickHandler, moveHandler }

  // ==================== iframe 辅助函数 ====================

  function getSameOriginIframes() {
    const result = [];
    document.querySelectorAll('iframe').forEach(iframe => {
      try {
        if (iframe.contentDocument && iframe.contentDocument.body) {
          result.push(iframe);
        }
      } catch (e) { /* 跨域忽略 */ }
    });
    return result;
  }

  function getElementIframe(element) {
    if (element.ownerDocument === document) return null;
    const iframes = document.querySelectorAll('iframe');
    for (const iframe of iframes) {
      try {
        if (iframe.contentDocument === element.ownerDocument) return iframe;
      } catch (e) { /* 跨域忽略 */ }
    }
    return null;
  }

  function getAbsoluteRect(element) {
    const rect = element.getBoundingClientRect();
    const iframe = getElementIframe(element);
    if (!iframe) return rect;
    const iframeRect = iframe.getBoundingClientRect();
    return {
      top: rect.top + iframeRect.top,
      left: rect.left + iframeRect.left,
      right: rect.right + iframeRect.left,
      bottom: rect.bottom + iframeRect.top,
      width: rect.width,
      height: rect.height
    };
  }

  function elementIsInDOM(element) {
    if (!element) return false;
    const doc = element.ownerDocument;
    return doc && doc.body && doc.body.contains(element);
  }

  // ==================== 初始化 ====================
  function init() {
    loadAnnotations();
    setupKeyboardShortcuts();
    setupGlobalScrollListener();
    createHoverOverlay();
    createSelectOverlay();
    console.log(`[Review Extension V2] ${t('initialized')}`);
  }

  // ==================== 全局滚动监听（架构改进3） ====================
  // 用捕获模式监听 document 上所有 scroll 事件，覆盖嵌套滚动容器
  function setupGlobalScrollListener() {
    const onScroll = () => {
      updateAllVisibleMarkerPositions();
      if (selectedElement) {
        updateSelectOverlay(selectedElement);
      }
      if (hoveredElement && isReviewMode) {
        updateHoverOverlay(hoveredElement);
      }
    };

    document.addEventListener('scroll', onScroll, true);

    // 监听 iframe 内滚动
    getSameOriginIframes().forEach(iframe => {
      try {
        iframe.contentDocument.addEventListener('scroll', onScroll, true);
      } catch (e) { /* 跨域忽略 */ }
    });

    // resize 同理
    window.addEventListener('resize', () => {
      updateAllVisibleMarkerPositions();
      if (selectedElement) {
        updateSelectOverlay(selectedElement);
      }
    });
  }

  // ==================== 快捷键监听 ====================
  function setupKeyboardShortcuts() {
    document.addEventListener('keydown', (e) => {
      if (e.key === 'Escape') {
        const currentTime = Date.now();
        if (currentTime - lastEscTime < ESC_DOUBLE_CLICK_THRESHOLD) {
          toggleReviewPanel();
          lastEscTime = 0;
        } else {
          lastEscTime = currentTime;
        }
      }
    });
  }

  // ==================== 评审面板 ====================
  function toggleReviewPanel() {
    if (isPanelVisible) {
      hideReviewPanel();
    } else {
      showReviewPanel();
    }
  }

  function showReviewPanel() {
    if (!reviewPanel) {
      createReviewPanel();
    }

    if (PANEL_ENTRANCE_ANIMATION === 'flip') {
      showReviewPanelFlip();
    } else {
      showReviewPanelDrop();
    }
  }

  // 出场方式1：从天砸落（原有动效）
  function showReviewPanelDrop() {
    reviewPanel.style.display = 'flex';

    // 重置位置到初始状态（底部居中），清除拖动后的定位
    reviewPanel.style.left = '50%';
    reviewPanel.style.top = 'auto';
    reviewPanel.style.bottom = '20px';
    reviewPanel.style.right = 'auto';
    reviewPanel.style.transform = 'translateX(-50%)';

    // 清除可能残留的其他动画类
    reviewPanel.classList.remove('dq-review-panel-drop', 'dq-review-panel-flip-in', 'dq-review-panel-exit');
    void reviewPanel.offsetWidth;
    reviewPanel.classList.add('dq-review-panel-drop');

    isPanelVisible = true;
    afterPanelShow();
  }

  // 出场方式2：翻转出场（双面卡片：背面 Logo → 翻转 → 正面按钮）
  function showReviewPanelFlip() {
    // 重置面板为相对定位（由 wrapper 控制位置）
    reviewPanel.style.display = 'flex';
    reviewPanel.style.position = 'relative';
    reviewPanel.style.left = 'auto';
    reviewPanel.style.top = 'auto';
    reviewPanel.style.bottom = 'auto';
    reviewPanel.style.right = 'auto';
    reviewPanel.style.transform = 'none';

    // 创建 wrapper 提供 perspective + 定位
    const wrapper = createFlipWrapper(false);
    wrapper.appendChild(reviewPanel);
    document.body.appendChild(wrapper);

    // 插入背面层（Logo 面）
    ensurePanelBackface();

    // 清除可能残留的其他动画类
    reviewPanel.classList.remove('dq-review-panel-drop', 'dq-review-panel-flip-in', 'dq-review-panel-exit');
    void reviewPanel.offsetWidth;
    reviewPanel.classList.add('dq-review-panel-flip-in');

    // 动画结束后：拆除 wrapper，恢复面板为 fixed 定位
    setTimeout(() => {
      removePanelBackface();
      reviewPanel.classList.remove('dq-review-panel-flip-in');
      unwrapPanel();
    }, 850);

    isPanelVisible = true;
    afterPanelShow();
  }

  // 创建翻转动画用的 wrapper 层
  function createFlipWrapper(isDragged) {
    let wrapper = document.querySelector('.dq-review-panel-flip-wrapper');
    if (wrapper) wrapper.remove();

    wrapper = document.createElement('div');
    wrapper.className = 'dq-review-panel-flip-wrapper';

    if (isDragged) {
      // 拖动后：wrapper 定位到面板当前位置
      const rect = reviewPanel.getBoundingClientRect();
      wrapper.classList.add('dq-flip-wrapper-dragged');
      wrapper.style.position = 'fixed';
      wrapper.style.left = rect.left + 'px';
      wrapper.style.top = rect.top + 'px';
    }

    return wrapper;
  }

  // 拆除 wrapper，恢复面板为独立 fixed 定位
  function unwrapPanel() {
    const wrapper = reviewPanel.parentElement;
    if (!wrapper || !wrapper.classList.contains('dq-review-panel-flip-wrapper')) return;

    // 恢复面板为 fixed + 底部居中
    reviewPanel.style.position = 'fixed';
    reviewPanel.style.left = '50%';
    reviewPanel.style.top = 'auto';
    reviewPanel.style.bottom = '20px';
    reviewPanel.style.right = 'auto';
    reviewPanel.style.transform = 'translateX(-50%)';

    document.body.appendChild(reviewPanel);
    wrapper.remove();
  }

  // 创建/确保背面层存在（与面板同色背景 + 黑色 Logo 居中）
  function ensurePanelBackface() {
    if (reviewPanel.querySelector('.dq-review-panel-backface')) return;
    const backface = document.createElement('div');
    backface.className = 'dq-review-panel-backface';
    const panelBg = getComputedStyle(reviewPanel).backgroundColor || '#2d2d2d';
    // 使用 backgroundColor 而非 background 简写，避免覆盖 CSS 的 background-image/size/position
    backface.style.backgroundColor = panelBg;
    const logoUrl = chrome.runtime.getURL('icons/pingshen.png');
    backface.style.backgroundImage = `url('${logoUrl}')`;
    backface.style.backgroundRepeat = 'no-repeat';
    backface.style.backgroundPosition = 'center center';
    backface.style.backgroundSize = '28px 28px';
    backface.style.filter = 'brightness(0)';
    reviewPanel.insertBefore(backface, reviewPanel.firstChild);
  }

  // 移除背面层
  function removePanelBackface() {
    const el = reviewPanel.querySelector('.dq-review-panel-backface');
    if (el) el.remove();
  }

  // 面板显示后的通用初始化
  function afterPanelShow() {
    rebuildAndShowMarkers();
    updateCommentBadge();

    setTimeout(() => {
      detectAndSwitchTheme();
    }, 100);
  }

  function hideReviewPanel() {
    if (!reviewPanel) return;

    // 判断是否被拖动过（拖动后 transform 不含 translateX(-50%)）
    const wasDragged = !reviewPanel.style.transform.includes('translateX(-50%)');

    // 退场动画：直接从当前位置向下滑出消失
    reviewPanel.classList.remove('dq-review-panel-drop', 'dq-review-panel-flip-in');
    void reviewPanel.offsetWidth;
    reviewPanel.classList.add('dq-review-panel-exit');
    if (wasDragged) {
      reviewPanel.classList.add('dq-exit-dragged');
    }

    // 动画结束后隐藏并重置
    setTimeout(() => {
      reviewPanel.style.display = 'none';
      reviewPanel.classList.remove('dq-review-panel-exit', 'dq-exit-dragged');
    }, 300);

    isPanelVisible = false;

    // 架构改进1：隐藏角标而非销毁
    hideAllMarkers();
    hideCommentList();
    hideSelectOverlay();

    if (isReviewMode) {
      exitReviewMode();
    }
  }

  function createReviewPanel() {
    reviewPanel = document.createElement('div');
    reviewPanel.className = 'dq-review-panel';
    reviewPanel.innerHTML = `
      <div class="dq-review-panel-drag-handle" title="${t('dragHandle')}">⋮⋮</div>
      <button class="dq-review-btn dq-review-btn-primary" id="reviewToggleBtn">${t('startReview')}</button>
      <button class="dq-review-btn dq-review-btn-secondary dq-review-btn-with-badge" id="reviewViewCommentsBtn">
        ${t('viewRecords')}
        <span class="dq-review-badge" id="reviewCommentBadge">0</span>
      </button>
      <button class="dq-review-btn dq-review-btn-secondary" id="reviewExportBtn">${t('export')}</button>
      <button class="dq-review-btn dq-review-btn-secondary" id="reviewBackupBtn">${t('backup')}</button>
      <button class="dq-review-btn-icon" id="reviewCloseBtn" title="${t('close')}">
        <svg width="16" height="16" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path d="M5 5L15 15M15 5L5 15" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"/>
        </svg>
      </button>
    `;

    document.body.appendChild(reviewPanel);

    document.getElementById('reviewToggleBtn').addEventListener('click', toggleReviewMode);
    document.getElementById('reviewViewCommentsBtn').addEventListener('click', toggleCommentList);
    document.getElementById('reviewExportBtn').addEventListener('click', showExportDialog);
    document.getElementById('reviewBackupBtn').addEventListener('click', showBackupMenu);
    document.getElementById('reviewCloseBtn').addEventListener('click', hideReviewPanel);

    const dragHandle = reviewPanel.querySelector('.dq-review-panel-drag-handle');
    dragHandle.addEventListener('mousedown', startDrag);
  }

  function updateCommentBadge() {
    const badge = document.getElementById('reviewCommentBadge');
    if (badge) {
      badge.textContent = annotations.length;
      badge.style.display = annotations.length > 0 ? 'flex' : 'none';
    }
  }

  // ==================== 拖动功能 ====================
  function startDrag(e) {
    isDragging = true;
    dragStartX = e.clientX;
    dragStartY = e.clientY;

    const rect = reviewPanel.getBoundingClientRect();
    panelStartX = rect.left;
    panelStartY = rect.top;

    // 移除所有动画类，避免 transform 冲突
    reviewPanel.classList.remove('dq-review-panel-drop', 'dq-review-panel-flip-in', 'dq-review-panel-exit');
    // 清除 transform，改用 left/top 定位
    reviewPanel.style.transform = 'none';
    reviewPanel.style.left = panelStartX + 'px';
    reviewPanel.style.top = panelStartY + 'px';
    reviewPanel.style.bottom = 'auto';

    document.addEventListener('mousemove', drag);
    document.addEventListener('mouseup', stopDrag);

    e.preventDefault();
  }

  function drag(e) {
    if (!isDragging) return;

    const deltaX = e.clientX - dragStartX;
    const deltaY = e.clientY - dragStartY;

    const newX = panelStartX + deltaX;
    const newY = panelStartY + deltaY;

    const maxX = window.innerWidth - reviewPanel.offsetWidth;
    const maxY = window.innerHeight - reviewPanel.offsetHeight;

    reviewPanel.style.left = Math.max(0, Math.min(newX, maxX)) + 'px';
    reviewPanel.style.top = Math.max(0, Math.min(newY, maxY)) + 'px';
    reviewPanel.style.right = 'auto';
    reviewPanel.style.bottom = 'auto';
  }

  function stopDrag() {
    isDragging = false;
    document.removeEventListener('mousemove', drag);
    document.removeEventListener('mouseup', stopDrag);

    // 拖动结束后检测周边颜色并切换主题
    setTimeout(() => {
      detectAndSwitchTheme();
    }, 100); // 延迟100ms，确保面板位置已更新
  }

  // ==================== 评审模式切换 ====================
  function toggleReviewMode() {
    if (isReviewMode) {
      exitReviewMode();
    } else {
      enterReviewMode();
    }
  }

  function enterReviewMode() {
    isReviewMode = true;
    document.body.style.cursor = 'crosshair';
    document.addEventListener('click', handleElementClick, true);
    document.addEventListener('mousemove', handleMouseMove, true);
    attachIframeListeners();

    const btn = document.getElementById('reviewToggleBtn');
    if (btn) {
      btn.textContent = t('endReview');
      btn.classList.remove('dq-review-btn-primary');
      btn.classList.add('dq-review-btn-danger');
    }
  }

  function exitReviewMode() {
    isReviewMode = false;
    document.body.style.cursor = 'default';
    document.removeEventListener('click', handleElementClick, true);
    document.removeEventListener('mousemove', handleMouseMove, true);
    detachIframeListeners();

    hideHoverOverlay();
    hoveredElement = null;
    hideMarkerPop();

    if (commentDialog) {
      closeCommentDialog();
    }

    const btn = document.getElementById('reviewToggleBtn');
    if (btn) {
      btn.textContent = t('startReview');
      btn.classList.remove('dq-review-btn-danger');
      btn.classList.add('dq-review-btn-primary');
    }
  }

  // iframe 事件注入/清理
  function attachIframeListeners() {
    detachIframeListeners();
    getSameOriginIframes().forEach(iframe => {
      try {
        const iframeDoc = iframe.contentDocument;
        // 用包装函数，把 iframe 内事件转换为主文档可处理的形式
        const clickHandler = (e) => {
          if (!isReviewMode) return;
          const target = e.target;
          if (target === iframeDoc.body || target === iframeDoc.documentElement) return;
          e.stopPropagation();
          hideHoverOverlay();
          hoveredElement = null;
          selectedElement = target;
          updateSelectOverlay(selectedElement);
          showCommentDialog(target);
        };
        const moveHandler = (e) => {
          if (!isReviewMode) return;
          const target = e.target;
          if (target === iframeDoc.body || target === iframeDoc.documentElement) {
            hideHoverOverlay();
            hoveredElement = null;
            return;
          }
          if (hoveredElement === target) return;
          hoveredElement = target;
          updateHoverOverlay(hoveredElement);
        };
        iframeDoc.addEventListener('click', clickHandler, true);
        iframeDoc.addEventListener('mousemove', moveHandler, true);
        iframeDoc.body.style.cursor = 'crosshair';
        iframeListeners.push({ iframe, doc: iframeDoc, clickHandler, moveHandler });
      } catch (e) {
        console.warn('[Review Extension V2] iframe attach failed:', e.message);
      }
    });
  }

  function detachIframeListeners() {
    iframeListeners.forEach(({ doc, clickHandler, moveHandler }) => {
      try {
        doc.removeEventListener('click', clickHandler, true);
        doc.removeEventListener('mousemove', moveHandler, true);
        doc.body.style.cursor = 'default';
      } catch (e) { /* iframe 可能已移除 */ }
    });
    iframeListeners = [];
  }

  // ==================== 覆盖层管理（架构改进4） ====================
  // 覆盖层在 init 时就创建，生命周期独立于评审模式

  function createHoverOverlay() {
    if (hoverOverlay) return;
    hoverOverlay = document.createElement('div');
    hoverOverlay.style.cssText = `
      position: fixed;
      pointer-events: none;
      z-index: 2147483645;
      border: 2px dashed #93c5fd;
      background: rgba(147, 197, 253, 0.05);
      display: none;
      box-sizing: border-box;
    `;
    document.body.appendChild(hoverOverlay);
  }

  function updateHoverOverlay(element) {
    if (!hoverOverlay || !element) return;
    const rect = getAbsoluteRect(element);
    hoverOverlay.style.display = 'block';
    hoverOverlay.style.top = rect.top + 'px';
    hoverOverlay.style.left = rect.left + 'px';
    hoverOverlay.style.width = rect.width + 'px';
    hoverOverlay.style.height = rect.height + 'px';
  }

  function hideHoverOverlay() {
    if (hoverOverlay) {
      hoverOverlay.style.display = 'none';
    }
  }

  function createSelectOverlay() {
    if (selectOverlay) return;
    selectOverlay = document.createElement('div');
    selectOverlay.style.cssText = `
      position: fixed;
      pointer-events: none;
      z-index: 2147483644;
      border: 3px dashed #fbbf24;
      background: rgba(251, 191, 36, 0.05);
      display: none;
      box-sizing: border-box;
    `;
    document.body.appendChild(selectOverlay);
  }

  function updateSelectOverlay(element) {
    if (!selectOverlay || !element) return;
    const rect = getAbsoluteRect(element);
    selectOverlay.style.display = 'block';
    selectOverlay.style.top = rect.top + 'px';
    selectOverlay.style.left = rect.left + 'px';
    selectOverlay.style.width = rect.width + 'px';
    selectOverlay.style.height = rect.height + 'px';
  }

  function hideSelectOverlay() {
    if (selectOverlay) {
      selectOverlay.style.display = 'none';
    }
    selectedElement = null;
  }

  // ==================== 鼠标事件处理 ====================
  function handleMouseMove(e) {
    if (!isReviewMode) return;

    if (isReviewUIElement(e.target) || e.target === document.body || e.target === document.documentElement) {
      hideHoverOverlay();
      hoveredElement = null;
      document.body.style.cursor = 'default';
      return;
    }

    document.body.style.cursor = 'crosshair';

    if (hoveredElement === e.target) return;

    hoveredElement = e.target;
    updateHoverOverlay(hoveredElement);
  }

  function handleElementClick(e) {
    if (!isReviewMode) return;

    // 先判断是否评审工具自身的 UI 元素（必须在 isConnected 检查之前，以处理菜单已移除的边缘情况）
    if (isReviewUIElement(e.target)) {
      return;
    }

    // 如果目标元素已从 DOM 移除（如备份菜单项被 closeMenu 先移除），跳过
    if (!document.contains(e.target)) return;
    // 跳过隐藏元素和下载链接（备份/导出功能通过程序化 .click() 触发的）
    if (e.target.style.display === 'none' || e.target.hasAttribute('download')) return;
    if (e.target === document.body || e.target === document.documentElement) return;

    e.stopPropagation();

    hideHoverOverlay();
    hoveredElement = null;

    selectedElement = e.target;
    updateSelectOverlay(selectedElement);

    showCommentDialog(e.target);
  }

  // 判断是否是评审工具自身的 UI 元素（通用前缀匹配，避免遗漏）
  function isReviewUIElement(target) {
    return !!target.closest('[class*="dq-review-"], [class*="dq-custom-"]');
  }

  // ==================== 评论对话框 ====================
  function setReviewPanelPointerEvents(disabled) {
    if (!reviewPanel) return;
    reviewPanel.style.pointerEvents = disabled ? 'none' : '';
  }

  function closeCommentDialog() {
    if (commentDialog) {
      commentDialog.remove();
      commentDialog = null;
    }
    setReviewPanelPointerEvents(false);
  }

  function showCommentDialog(element) {
    closeCommentDialog();

    commentDialog = document.createElement('div');
    commentDialog.className = 'dq-review-comment-dialog';
    commentDialog.innerHTML = `
      <div class="dq-review-dialog-header">${t('addComment')}</div>
      <div class="dq-review-dialog-body">
        <div class="dq-review-form-row">
          <div class="dq-review-form-group">
            <label>${t('type')}</label>
            <div class="dq-custom-select" id="reviewCommentTypeWrapper">
              <div class="dq-custom-select-trigger">
                <span class="dq-custom-select-value">${t('typeIssue')}</span>
                <svg class="dq-custom-select-arrow" width="12" height="12" viewBox="0 0 12 12">
                  <path fill="currentColor" d="M6 9L1 4h10z"/>
                </svg>
              </div>
              <div class="dq-custom-select-dropdown">
                <div class="dq-custom-select-option" data-value="${t('typeIssue')}">${t('typeIssue')}</div>
                <div class="dq-custom-select-option" data-value="${t('typeSuggestion')}">${t('typeSuggestion')}</div>
                <div class="dq-custom-select-option" data-value="${t('typeDecision')}">${t('typeDecision')}</div>
                <div class="dq-custom-select-option" data-value="${t('typePending')}">${t('typePending')}</div>
              </div>
            </div>
          </div>
          <div class="dq-review-form-group">
            <label>${t('priority')}</label>
            <div class="dq-custom-select" id="reviewCommentPriorityWrapper">
              <div class="dq-custom-select-trigger">
                <span class="dq-custom-select-value">${t('p0')}</span>
                <svg class="dq-custom-select-arrow" width="12" height="12" viewBox="0 0 12 12">
                  <path fill="currentColor" d="M6 9L1 4h10z"/>
                </svg>
              </div>
              <div class="dq-custom-select-dropdown">
                <div class="dq-custom-select-option" data-value="P0">${t('p0')}</div>
                <div class="dq-custom-select-option" data-value="P1">${t('p1')}</div>
                <div class="dq-custom-select-option" data-value="P2">${t('p2')}</div>
              </div>
            </div>
          </div>
        </div>
        <div class="dq-review-form-group">
          <label>${t('commentContent')} <span style="color:#ef4444;">*</span></label>
          <textarea id="reviewCommentContent" class="dq-review-form-control" rows="5" placeholder="${t('commentPlaceholder')}"></textarea>
        </div>
      </div>
      <div class="dq-review-dialog-footer">
        <button class="dq-review-btn dq-review-btn-secondary" id="reviewCancelBtn">${t('cancel')}</button>
        <button class="dq-review-btn dq-review-btn-primary" id="reviewSaveBtn">${t('save')}</button>
      </div>
    `;

    document.body.appendChild(commentDialog);

    const rect = getAbsoluteRect(element);
    const dialogWidth = 400;
    const dialogHeight = 380;

    let left = rect.right + 10;
    let top = rect.top;

    if (left + dialogWidth > window.innerWidth) {
      left = rect.left - dialogWidth - 10;
    }
    if (left < 0) {
      left = (window.innerWidth - dialogWidth) / 2;
    }
    if (top + dialogHeight > window.innerHeight) {
      top = window.innerHeight - dialogHeight - 20;
    }
    if (top < 0) {
      top = 20;
    }

    commentDialog.style.left = left + 'px';
    commentDialog.style.top = top + 'px';
    setReviewPanelPointerEvents(true);

    document.getElementById('reviewCancelBtn').addEventListener('click', () => {
      closeCommentDialog();
      hideSelectOverlay();
    });

    document.getElementById('reviewSaveBtn').addEventListener('click', () => {
      saveComment(element);
    });

    // 初始化自定义下拉框
    initCustomSelects();

    document.getElementById('reviewCommentContent').focus();
  }

  /**
   * 初始化所有自定义下拉框的交互逻辑
   */
  function initCustomSelects() {
    document.querySelectorAll('.dq-custom-select').forEach(select => {
      const trigger = select.querySelector('.dq-custom-select-trigger');
      const dropdown = select.querySelector('.dq-custom-select-dropdown');
      const valueDisplay = select.querySelector('.dq-custom-select-value');
      const options = select.querySelectorAll('.dq-custom-select-option');

      // 设置默认值
      if (options.length > 0) {
        select.dataset.value = options[0].dataset.value;
        options[0].classList.add('dq-selected');
      }

      // 点击触发器，展开/收起下拉菜单
      trigger.addEventListener('click', (e) => {
        e.stopPropagation();
        // 关闭其他已打开的下拉框
        document.querySelectorAll('.dq-custom-select.dq-open').forEach(other => {
          if (other !== select) other.classList.remove('dq-open');
        });
        select.classList.toggle('dq-open');
      });

      // 点击选项
      options.forEach(option => {
        option.addEventListener('click', (e) => {
          e.stopPropagation();
          select.dataset.value = option.dataset.value;
          valueDisplay.textContent = option.textContent;
          options.forEach(o => o.classList.remove('dq-selected'));
          option.classList.add('dq-selected');
          select.classList.remove('dq-open');
        });
      });
    });

    // 点击其他区域关闭下拉框
    document.addEventListener('click', () => {
      document.querySelectorAll('.dq-custom-select.dq-open').forEach(select => {
        select.classList.remove('dq-open');
      });
    });
  }

  // ==================== 保存评论 ====================
  function saveComment(element) {
    const type = document.getElementById('reviewCommentTypeWrapper').dataset.value || t('typeIssue');
    const priority = document.getElementById('reviewCommentPriorityWrapper').dataset.value || 'P0';
    const content = document.getElementById('reviewCommentContent').value.trim();

    if (!content) {
      showToast(t('pleaseEnterContent'));
      return;
    }

    currentAnnotationId++;
    const annotationId = currentAnnotationId;

    const selector = getElementSelector(element);

    const annotation = {
      id: annotationId,
      type,
      priority,
      content,
      selector,
      timestamp: new Date().toISOString()
    };

    annotations.push(annotation);
    saveAnnotations();

    // 建立运行时映射
    annotationElementMap.set(annotationId, element);

    // 创建角标（不会被销毁，只切换显示）
    createMarker(annotation, element);

    closeCommentDialog();

    hideSelectOverlay();
    updateCommentBadge();
  }

  // ==================== 角标管理（架构改进1） ====================
  // 角标只创建一次，只切换 display 状态，不销毁

  function createMarker(annotation, element) {
    // 如果已存在，不重复创建
    if (annotationMarkerMap.has(annotation.id)) return;

    const marker = document.createElement('div');
    marker.className = 'dq-review-marker';
    marker.textContent = annotation.id;
    marker.dataset.annotationId = annotation.id;
    marker.dataset.type = annotation.type;

    document.body.appendChild(marker);
    updateMarkerPosition(marker, element);

    // 角标点击：双向联动（隐藏 pop，打开列表）
    marker.addEventListener('click', (e) => {
      e.stopPropagation();
      hideMarkerPop();

      // 显示黄色参考框
      selectedElement = element;
      updateSelectOverlay(element);

      // 打开评论列表并高亮对应卡片
      showCommentList();
      highlightCommentCard(annotation.id);
    });

    // hover 显示 pop 弹窗
    marker.addEventListener('mouseenter', () => {
      clearPopHideTimer();
      showMarkerPop(marker, annotation);
    });
    marker.addEventListener('mouseleave', () => {
      if (!popIsEditing) scheduleHidePop();
    });

    // 存入映射表
    annotationMarkerMap.set(annotation.id, { marker, element });
  }

  function updateMarkerPosition(marker, element) {
    if (!element || !elementIsInDOM(element)) {
      marker.style.display = 'none';
      return;
    }

    const rect = getAbsoluteRect(element);

    // 判断元素是否在视口外（被滚动隐藏）
    // 如果元素完全不可见，隐藏角标
    if (rect.bottom < 0 || rect.top > window.innerHeight ||
        rect.right < 0 || rect.left > window.innerWidth) {
      marker.style.display = 'none';
      return;
    }

    marker.style.position = 'fixed';
    marker.style.top = (rect.top - 10) + 'px';
    marker.style.left = (rect.right - 10) + 'px';
    marker.style.display = 'flex';
  }

  // 更新所有可见角标位置
  function updateAllVisibleMarkerPositions() {
    if (!isPanelVisible) return; // 面板隐藏时不需要更新

    annotationMarkerMap.forEach(({ marker, element }, annotationId) => {
      // 如果运行时引用丢失（页面刷新后），尝试重新查找
      if (!element || !elementIsInDOM(element)) {
        const annotation = annotations.find(a => a.id === annotationId);
        if (annotation) {
          const found = findElementSafe(annotation.selector);
          if (found) {
            annotationMarkerMap.set(annotationId, { marker, element: found });
            annotationElementMap.set(annotationId, found);
            element = found;
          }
        }
      }
      updateMarkerPosition(marker, element);
    });
  }

  // 重建角标并显示（面板打开时调用）
  function rebuildAndShowMarkers() {
    let bounceIndex = 0;
    annotations.forEach(annotation => {
      if (annotationMarkerMap.has(annotation.id)) {
        // 角标已存在，显示并更新位置
        const { marker, element } = annotationMarkerMap.get(annotation.id);
        // 检查元素是否还在 DOM 中
        if (element && elementIsInDOM(element)) {
          updateMarkerPosition(marker, element);
          triggerBounce(marker, bounceIndex++);
        } else {
          // 运行时引用丢失，尝试通过 selector 找回
          const found = findElementSafe(annotation.selector);
          if (found) {
            annotationMarkerMap.set(annotation.id, { marker, element: found });
            annotationElementMap.set(annotation.id, found);
            updateMarkerPosition(marker, found);
            triggerBounce(marker, bounceIndex++);
          } else {
            marker.style.display = 'none';
          }
        }
      } else {
        // 角标不存在（首次加载或页面刷新后），创建
        const element = findElementSafe(annotation.selector);
        if (element) {
          annotationElementMap.set(annotation.id, element);
          createMarker(annotation, element);
          const entry = annotationMarkerMap.get(annotation.id);
          if (entry) triggerBounce(entry.marker, bounceIndex++);
        }
      }
    });
  }

  // Q弹入场：错开时间依次弹出
  function triggerBounce(marker, index) {
    // 先隐藏（scale(0)），等延迟后再弹出
    marker.style.setProperty('transform', 'scale(0)', 'important');
    marker.classList.remove('dq-marker-bounce');
    setTimeout(() => {
      marker.style.removeProperty('transform');
      marker.classList.add('dq-marker-bounce');
      marker.addEventListener('animationend', () => {
        marker.classList.remove('dq-marker-bounce');
      }, { once: true });
    }, index * 80);
  }

  // 隐藏所有角标（面板关闭时调用，不销毁）
  function hideAllMarkers() {
    annotationMarkerMap.forEach(({ marker }) => {
      marker.style.display = 'none';
    });
    hideMarkerPop();
  }

  // ==================== 角标 Pop 弹窗 ====================

  let activeMarkerPop = null;   // 当前显示的 pop DOM
  let activePopAnnotationId = null; // 当前 pop 对应的 annotation id
  let popHideTimer = null;      // 延迟隐藏定时器
  let popIsEditing = false;     // 是否正在编辑

  function showMarkerPop(marker, annotation) {
    // 如果正在编辑当前 pop，不重复打开
    if (popIsEditing && activePopAnnotationId === annotation.id) return;

    // 如果是同一个 annotation 且已显示，保持不动
    if (activeMarkerPop && activePopAnnotationId === annotation.id && !popIsEditing) {
      clearPopHideTimer();
      return;
    }

    hideMarkerPop();

    activePopAnnotationId = annotation.id;

    const pop = document.createElement('div');
    pop.className = 'dq-review-marker-pop';
    pop.style.setProperty('padding', '8px', 'important');

    const popContent = document.createElement('div');
    popContent.className = 'dq-review-marker-pop-content';
    popContent.textContent = annotation.content || '';

    const arrow = document.createElement('div');
    arrow.className = 'dq-review-marker-pop-arrow dq-arrow-bottom';

    pop.appendChild(arrow);
    pop.appendChild(popContent);

    document.body.appendChild(pop);
    activeMarkerPop = pop;

    // 定位到 marker 上方
    positionPop(pop, marker);

    // 淡入
    requestAnimationFrame(() => pop.classList.add('dq-pop-visible'));

    // pop 区域的 mouseenter/mouseleave 保持显示
    pop.addEventListener('mouseenter', () => clearPopHideTimer());
    pop.addEventListener('mouseleave', () => {
      if (!popIsEditing) scheduleHidePop();
    });

    // 点击内容区进入编辑模式
    const contentEl = pop.querySelector('.dq-review-marker-pop-content');
    contentEl.addEventListener('click', (e) => {
      e.stopPropagation();
      enterPopEdit(pop, annotation);
    });
  }

  function positionPop(pop, marker) {
    const markerRect = marker.getBoundingClientRect();
    const popRect = pop.getBoundingClientRect();
    const arrow = pop.querySelector('.dq-review-marker-pop-arrow');
    const gap = 8;
    const edge = 4; // 距视口边缘最小间距
    const vw = window.innerWidth;
    const vh = window.innerHeight;

    // ---- 1. 垂直方向：优先上方，空间不够放下方 ----
    const spaceAbove = markerRect.top;
    const spaceBelow = vh - markerRect.bottom;
    let arrowDir;

    pop.style.position = 'fixed';

    if (spaceAbove >= popRect.height + gap + edge) {
      // 上方够：用 bottom 锚定，编辑态向上延展
      pop.style.top = '';
      pop.style.bottom = (vh - markerRect.top + gap) + 'px';
      arrowDir = 'bottom';
    } else if (spaceBelow >= popRect.height + gap + edge) {
      // 下方够：用 top 锚定
      pop.style.bottom = '';
      pop.style.top = (markerRect.bottom + gap) + 'px';
      arrowDir = 'top';
    } else {
      // 上下都不够：选空间大的一侧，限制 pop 高度
      if (spaceAbove >= spaceBelow) {
        pop.style.top = '';
        pop.style.bottom = (vh - markerRect.top + gap) + 'px';
        pop.style.maxHeight = (spaceAbove - gap - edge) + 'px';
        arrowDir = 'bottom';
      } else {
        pop.style.bottom = '';
        pop.style.top = (markerRect.bottom + gap) + 'px';
        pop.style.maxHeight = (spaceBelow - gap - edge) + 'px';
        arrowDir = 'top';
      }
    }

    // ---- 2. 水平方向：居中对齐 marker，贴边修正 ----
    let left = markerRect.left + markerRect.width / 2 - popRect.width / 2;

    if (left < edge) left = edge;
    if (left + popRect.width > vw - edge) left = vw - popRect.width - edge;

    pop.style.left = left + 'px';

    // ---- 3. 箭头：始终指向 marker 中心 ----
    arrow.className = 'dq-review-marker-pop-arrow';
    arrow.classList.add(arrowDir === 'bottom' ? 'dq-arrow-bottom' : 'dq-arrow-top');
    const markerCenterX = markerRect.left + markerRect.width / 2;
    const arrowLeft = markerCenterX - left - 5;
    arrow.style.left = Math.max(10, Math.min(arrowLeft, popRect.width - 18)) + 'px';
  }

  function enterPopEdit(pop, annotation) {
    if (popIsEditing) return;
    popIsEditing = true;

    const contentEl = pop.querySelector('.dq-review-marker-pop-content');
    const currentText = annotation.content || '';

    // 直接替换为 textarea，边距由 pop 容器 padding 统一控制
    const textarea = document.createElement('textarea');
    textarea.className = 'dq-review-marker-pop-edit';
    textarea.value = currentText;
    contentEl.replaceWith(textarea);

    textarea.focus();
    // 光标移到末尾
    textarea.setSelectionRange(textarea.value.length, textarea.value.length);

    // 失焦：保存 + 关闭
    textarea.addEventListener('blur', () => {
      const newText = textarea.value.trim();
      if (newText && newText !== annotation.content) {
        annotation.content = newText;
        saveAnnotations();
        updateCommentList();
      }
      popIsEditing = false;
      hideMarkerPop();
    });

    // Esc 取消编辑
    textarea.addEventListener('keydown', (e) => {
      if (e.key === 'Escape') {
        e.stopPropagation();
        popIsEditing = false;
        hideMarkerPop();
      }
    });

    // 阻止事件冒泡，避免触发 handleElementClick 等
    textarea.addEventListener('click', (e) => e.stopPropagation());
    textarea.addEventListener('mousedown', (e) => e.stopPropagation());
  }

  function hideMarkerPop() {
    clearPopHideTimer();
    if (activeMarkerPop) {
      activeMarkerPop.remove();
      activeMarkerPop = null;
      activePopAnnotationId = null;
      popIsEditing = false;
    }
  }

  function scheduleHidePop() {
    clearPopHideTimer();
    popHideTimer = setTimeout(() => hideMarkerPop(), 200);
  }

  function clearPopHideTimer() {
    if (popHideTimer) {
      clearTimeout(popHideTimer);
      popHideTimer = null;
    }
  }

  // ==================== 增强的元素选择器（架构改进2） ====================

  function getElementSelector(element) {
    const iframe = getElementIframe(element);
    const baseSelector = getElementSelectorInDoc(element);
    if (!iframe) return baseSelector;
    // iframe 内元素：生成 IFRAME[src="..."] >> selector 格式
    const iframeSelector = getElementSelectorInDoc(iframe);
    return iframeSelector + ' >> ' + baseSelector;
  }

  function getElementSelectorInDoc(element) {
    // 优先用 ID（最稳定）
    if (element.id) {
      return '#' + cssEscape(element.id);
    }

    const path = [];
    let current = element;

    while (current && current.nodeType === Node.ELEMENT_NODE) {
      let selector = current.nodeName.toLowerCase();

      // 用 CSS.escape 安全转义 class 名
      if (current.className && typeof current.className === 'string') {
        const classes = current.className.split(' ')
          .filter(c => c.trim() && !c.startsWith('dq-review-'))
          .map(c => cssEscape(c.trim()));
        if (classes.length > 0) {
          selector += '.' + classes.join('.');
        }
      }

      // nth-child 保证唯一性
      if (current.parentNode) {
        const siblings = Array.from(current.parentNode.children);
        const index = siblings.indexOf(current) + 1;
        selector += `:nth-child(${index})`;
      }

      path.unshift(selector);
      current = current.parentNode;

      if (current && (current.nodeName === 'BODY' || current.nodeName === 'HTML')) {
        break;
      }

      if (path.length > 8) break;
    }

    return path.join(' > ');
  }

  // CSS.escape polyfill（兼容不支持的环境）
  function cssEscape(value) {
    if (typeof CSS !== 'undefined' && CSS.escape) {
      return CSS.escape(value);
    }
    // 手动转义特殊字符
    return value.replace(/([^\w-])/g, '\\$1');
  }

  // 安全查找元素（容错，支持 iframe）
  function findElementSafe(selector) {
    if (!selector) return null;

    // 检查是否是 iframe 内元素（包含 >> 分隔符）
    const iframeSplit = selector.indexOf(' >> ');
    if (iframeSplit !== -1) {
      const iframeSel = selector.substring(0, iframeSplit);
      const innerSel = selector.substring(iframeSplit + 4);
      try {
        const iframe = document.querySelector(iframeSel);
        if (iframe && iframe.contentDocument) {
          return queryWithFallback(iframe.contentDocument, innerSel);
        }
      } catch (e) {
        console.warn('[Review Extension V2] iframe selector failed:', e.message);
      }
      return null;
    }

    return queryWithFallback(document, selector);
  }

  function queryWithFallback(doc, selector) {
    try {
      return doc.querySelector(selector);
    } catch (e) {
      console.warn('[Review Extension V2]', t('selectorFailed'), selector, e.message);
      // 备用：去掉类名部分，只用标签 + nth-child
      try {
        const simplified = selector.replace(/\.[^:>\s]+/g, '');
        if (simplified !== selector) {
          return doc.querySelector(simplified);
        }
      } catch (e2) {
        console.warn('[Review Extension V2]', t('backupFailed'), e2.message);
      }
      return null;
    }
  }

  // ==================== 评论列表面板 ====================
  function toggleCommentList() {
    if (commentListPanel && commentListPanel.classList.contains('show')) {
      hideCommentList();
    } else {
      showCommentList();
    }
  }

  function showCommentList() {
    if (!commentListPanel) {
      createCommentListPanel();
    }

    updateCommentList();
    commentListPanel.classList.add('show');
  }

  function hideCommentList() {
    if (commentListPanel) {
      commentListPanel.classList.remove('show');
    }
  }

  function createCommentListPanel() {
    commentListPanel = document.createElement('div');
    commentListPanel.className = 'dq-review-comment-list';
    commentListPanel.innerHTML = `
      <div class="dq-review-comment-list-header">
        <span>${t('reviewRecords')}</span>
        <button class="dq-review-close-btn" id="reviewCloseListBtn">
          <svg class="dq-review-close-icon" width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M5 5L15 15M15 5L5 15" stroke="#6b7280" stroke-width="2.5" stroke-linecap="round"/>
          </svg>
        </button>
      </div>
      <div class="dq-review-comment-list-body" id="reviewCommentListBody">
      </div>
    `;

    document.body.appendChild(commentListPanel);

    document.getElementById('reviewCloseListBtn').addEventListener('click', hideCommentList);

    // 点击外部区域隐藏面板
    document.addEventListener('click', (e) => {
      if (commentListPanel &&
          commentListPanel.classList.contains('show') &&
          !e.target.closest('.dq-review-comment-list') &&
          !e.target.closest('#reviewViewCommentsBtn') &&
          !e.target.closest('.dq-review-marker')) {
        hideCommentList();
      }
    }, true);
  }

  function updateCommentList() {
    const listBody = document.getElementById('reviewCommentListBody');
    if (!listBody) return;

    if (annotations.length === 0) {
      listBody.innerHTML = `
        <div class="dq-review-empty-state">
          <div style="font-size:36px;margin-bottom:12px;opacity:0.3;">&#128221;</div>
          <div style="font-size:15px;font-weight:600;color:#374151;margin-bottom:16px;">${t('noComments')}</div>
          <div style="text-align:left;background:#f9fafb;border:1px solid #e5e7eb;border-radius:10px;padding:16px 20px;font-size:13px;line-height:2;color:#6b7280;">
            <div style="font-weight:600;color:#374151;margin-bottom:8px;font-size:14px;">${t('guideTitle')}</div>
            <div><span style="color:#667eea;font-weight:600;">1.</span> ${t('guide1')}</div>
            <div><span style="color:#667eea;font-weight:600;">2.</span> ${t('guide2')}</div>
            <div><span style="color:#667eea;font-weight:600;">3.</span> ${t('guide3')}</div>
            <div><span style="color:#667eea;font-weight:600;">4.</span> ${t('guide4')}</div>
            <div><span style="color:#667eea;font-weight:600;">5.</span> ${t('guide5')}</div>
            <div><span style="color:#667eea;font-weight:600;">6.</span> ${t('guide6')}</div>
          </div>
        </div>
      `;
      return;
    }

    const sortedAnnotations = [...annotations].sort((a, b) => {
      const priorityOrder = { 'P0': 0, 'P1': 1, 'P2': 2 };
      return priorityOrder[a.priority] - priorityOrder[b.priority];
    });

    listBody.innerHTML = sortedAnnotations.map(annotation => `
      <div class="dq-review-comment-item" data-annotation-id="${annotation.id}" data-type="${annotation.type}">
        <div class="dq-review-comment-item-header">
          <span class="dq-review-comment-number">${annotation.id}</span>
          <span class="dq-review-comment-badge dq-review-badge-${annotation.priority.toLowerCase()}">${annotation.priority}</span>
          <span class="dq-review-comment-type">[${annotation.type}]</span>
          <button class="dq-review-edit-btn" data-annotation-id="${annotation.id}" title="${t('edit')}">
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
              <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"></path>
              <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"></path>
            </svg>
          </button>
          <button class="dq-review-delete-btn" data-annotation-id="${annotation.id}" title="${t('delete')}">
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
              <polyline points="3 6 5 6 21 6"></polyline>
              <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path>
              <line x1="10" y1="11" x2="10" y2="17"></line>
              <line x1="14" y1="11" x2="14" y2="17"></line>
            </svg>
          </button>
        </div>
        <div class="dq-review-comment-item-content">${escapeHtml(annotation.content)}</div>
      </div>
    `).join('');

    // 卡片点击：双向联动
    listBody.querySelectorAll('.dq-review-comment-item').forEach(itemEl => {
      const annotationId = parseInt(itemEl.dataset.annotationId);

      itemEl.addEventListener('click', function(e) {
        if (e.target.closest('.dq-review-delete-btn') || e.target.closest('.dq-review-edit-btn')) return;

        // 选中卡片
        document.querySelectorAll('.dq-review-comment-item').forEach(el => el.classList.remove('selected'));
        this.classList.add('selected');

        // 定位到标注
        locateAnnotation(annotationId);
      });
    });

    // 编辑按钮
    listBody.querySelectorAll('.dq-review-edit-btn').forEach(btn => {
      btn.addEventListener('click', function(e) {
        e.stopPropagation();
        const annotationId = parseInt(this.dataset.annotationId);
        editAnnotation(annotationId);
      });
    });

    // 删除按钮
    listBody.querySelectorAll('.dq-review-delete-btn').forEach(btn => {
      btn.addEventListener('click', function(e) {
        e.stopPropagation();
        const annotationId = parseInt(this.dataset.annotationId);
        deleteAnnotation(annotationId);
      });
    });
  }

  // ==================== 双向联动核心 ====================

  function locateAnnotation(annotationId) {
    const annotation = annotations.find(a => a.id === annotationId);
    if (!annotation) return;

    // 优先从运行时映射获取，其次通过 selector 查找
    let element = annotationElementMap.get(annotationId);
    if (!element || !elementIsInDOM(element)) {
      element = findElementSafe(annotation.selector);
      if (element) {
        annotationElementMap.set(annotationId, element);
      }
    }

    if (element) {
      element.scrollIntoView({ behavior: 'smooth', block: 'center' });

      selectedElement = element;

      // 延迟更新位置，等 scrollIntoView 动画完成
      setTimeout(() => {
        updateSelectOverlay(element);
      }, 350);
    }

    // 高亮对应的评论卡片
    highlightCommentCard(annotationId);
  }

  function highlightCommentCard(annotationId) {
    const items = document.querySelectorAll('.dq-review-comment-item');
    items.forEach(item => {
      if (parseInt(item.dataset.annotationId) === annotationId) {
        item.classList.add('selected');
        item.scrollIntoView({ behavior: 'smooth', block: 'center' });
      } else {
        item.classList.remove('selected');
      }
    });
  }

  // ==================== 删除标注 ====================
  function deleteAnnotation(annotationId) {
    annotations = annotations.filter(a => a.id !== annotationId);
    saveAnnotations();

    // 销毁角标 DOM（删除是真删除）
    const entry = annotationMarkerMap.get(annotationId);
    if (entry && entry.marker) {
      entry.marker.remove();
    }
    annotationMarkerMap.delete(annotationId);
    annotationElementMap.delete(annotationId);

    // 如果当前选中的是被删除的标注，隐藏覆盖层
    hideSelectOverlay();

    updateCommentList();
    updateCommentBadge();
  }

  // ==================== 编辑标注 ====================
  function editAnnotation(annotationId) {
    const annotation = annotations.find(a => a.id === annotationId);
    if (!annotation) return;

    const itemEl = document.querySelector(`.dq-review-comment-item[data-annotation-id="${annotationId}"]`);
    if (!itemEl) return;

    const contentEl = itemEl.querySelector('.dq-review-comment-item-content');
    if (!contentEl) return;

    if (contentEl.querySelector('textarea')) return;

    const originalContent = annotation.content;

    const textarea = document.createElement('textarea');
    textarea.className = 'dq-review-edit-textarea';
    textarea.value = originalContent;
    textarea.style.cssText = `
      width: 100%;
      min-height: 80px;
      padding: 8px;
      border: 1px solid #667eea;
      border-radius: 6px;
      font-size: 14px;
      font-family: inherit;
      resize: vertical;
      box-sizing: border-box;
    `;

    const btnContainer = document.createElement('div');
    btnContainer.style.cssText = `
      display: flex;
      gap: 8px;
      margin-top: 8px;
      justify-content: flex-end;
    `;

    const saveBtn = document.createElement('button');
    saveBtn.textContent = t('save');
    saveBtn.className = 'dq-review-btn dq-review-btn-primary';
    saveBtn.style.cssText = `
      padding: 6px 12px;
      border: none;
      border-radius: 4px;
      font-size: 13px;
      font-weight: 500;
      cursor: pointer;
      background: #667eea;
      color: white;
    `;
    saveBtn.onclick = (e) => {
      e.stopPropagation();
      const newContent = textarea.value.trim();
      if (newContent && newContent !== originalContent) {
        annotation.content = newContent;
        saveAnnotations();
      }
      updateCommentList();
    };

    const cancelBtn = document.createElement('button');
    cancelBtn.textContent = t('cancel');
    cancelBtn.className = 'dq-review-btn dq-review-btn-secondary';
    cancelBtn.style.cssText = `
      padding: 6px 12px;
      border: none;
      border-radius: 4px;
      font-size: 13px;
      font-weight: 500;
      cursor: pointer;
      background: #e5e7eb;
      color: #374151;
    `;
    cancelBtn.onclick = (e) => {
      e.stopPropagation();
      updateCommentList();
    };

    btnContainer.appendChild(saveBtn);
    btnContainer.appendChild(cancelBtn);

    contentEl.innerHTML = '';
    contentEl.appendChild(textarea);
    contentEl.appendChild(btnContainer);

    textarea.focus();
    textarea.select();
  }

  // ==================== 备份菜单 ====================
  function showBackupMenu() {
    // 移除已有的菜单
    const existing = document.querySelector('.dq-review-backup-menu');
    if (existing) { existing.remove(); return; }

    const menu = document.createElement('div');
    menu.className = 'dq-review-backup-menu';
    menu.innerHTML = `
      <div class="dq-review-backup-menu-title">${t('backupTitle')}</div>
      <button class="dq-review-backup-menu-item" id="reviewBackupJsonBtn">${t('backupToJson')}</button>
      <button class="dq-review-backup-menu-item" id="reviewBackupHtmlBtn">${t('backupToHtml')}</button>
      <button class="dq-review-backup-menu-item" id="reviewRestoreBtn">${t('restoreFromBackup')}</button>
    `;

    // 定位到备份按钮上方
    const backupBtn = document.getElementById('reviewBackupBtn');
    const btnRect = backupBtn.getBoundingClientRect();
    menu.style.position = 'fixed';
    menu.style.left = `${btnRect.left}px`;
    menu.style.bottom = `${window.innerHeight - btnRect.top + 8}px`;
    menu.style.zIndex = '2147483647';

    document.body.appendChild(menu);

    document.getElementById('reviewBackupJsonBtn').addEventListener('click', (e) => {
      e.stopPropagation();
      manualJsonBackup();
      menu.remove();
    });

    document.getElementById('reviewBackupHtmlBtn').addEventListener('click', (e) => {
      e.stopPropagation();
      exportHtmlWithReviews();
      menu.remove();
    });

    document.getElementById('reviewRestoreBtn').addEventListener('click', (e) => {
      e.stopPropagation();
      restoreFromFileInput();
      menu.remove();
    });

    // 点击其他区域关闭菜单
    const closeMenu = (e) => {
      if (!menu.contains(e.target) && e.target !== backupBtn) {
        menu.remove();
        document.removeEventListener('click', closeMenu, true);
      }
    };
    setTimeout(() => document.addEventListener('click', closeMenu, true), 0);
  }

  // 手动触发 JSON 备份（不受每日一次限制）
  function manualJsonBackup() {
    if (annotations.length === 0) {
      showToast(t('noCommentsToExport'));
      return;
    }

    const backupData = {
      storageKey: getStorageKey(),
      annotations,
      currentId: currentAnnotationId,
      pageUrl: window.location.href,
      pageTitle: document.title,
      backupDate: new Date().toISOString().slice(0, 10),
      backupTime: new Date().toISOString()
    };

    const blob = new Blob([JSON.stringify(backupData, null, 2)], { type: 'application/json;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const pageName = window.location.pathname.split('/').pop().replace('.html', '') || 'prototype';
    const today = new Date().toISOString().slice(0, 10);
    const filename = `${pageName}-review-backup-${today}.json`;

    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.style.display = 'none';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    showToast(t('jsonBackupDone'));
  }

  // 从文件恢复评审数据
  function restoreFromFileInput() {
    const input = document.createElement('input');
    input.type = 'file';
    input.accept = '.json,.html';
    input.className = 'dq-review-file-input';
    input.style.display = 'none';

    input.addEventListener('change', (e) => {
      const file = e.target.files[0];
      if (!file) return;

      const reader = new FileReader();
      reader.onload = (ev) => {
        const content = ev.target.result;

        try {
          let restoredData = null;

          if (file.name.endsWith('.json')) {
            restoredData = JSON.parse(content);
          } else if (file.name.endsWith('.html')) {
            const match = content.match(/<!-- REVIEW_EXTENSION_DATA\n([\s\S]*?)\nEND_REVIEW_EXTENSION_DATA -->/);
            if (match) {
              restoredData = JSON.parse(match[1]);
            }
          }

          if (restoredData && restoredData.annotations && restoredData.annotations.length > 0) {
            const doRestore = () => {
              annotations = restoredData.annotations;
              currentAnnotationId = restoredData.currentId || restoredData.annotations.length;
              saveAnnotations();
              showToast(`${t('backupRestored')}（${annotations.length} ${t('commentsCount')}）`);
              // 刷新角标和标注
              updateCommentBadge();
              rebuildAndShowMarkers();
              updateCommentList();
            };

            // 校验备份是否属于当前页面
            const currentKey = getStorageKey();
            const backupKey = restoredData.storageKey || '';
            if (backupKey && backupKey !== currentKey) {
              const backupInfo = restoredData.pageTitle || backupKey;
              const currentInfo = document.title || currentKey;
              showRestoreConfirmDialog(backupInfo, currentInfo, doRestore);
            } else {
              doRestore();
            }
          } else {
            showToast(t('noBackupFound'));
          }
        } catch (err) {
          console.error('[Review Extension V2] restore error:', err);
          showToast(t('noBackupFound'));
        }
      };

      reader.readAsText(file);
      input.remove();
    });

    document.body.appendChild(input);
    input.click();
  }

  // 备份来源不匹配时的自定义确认弹窗（复用导出弹窗样式）
  function showRestoreConfirmDialog(backupInfo, currentInfo, onConfirm) {
    const dialog = document.createElement('div');
    dialog.className = 'dq-review-export-dialog';
    dialog.innerHTML = `
      <div class="dq-review-export-overlay"></div>
      <div class="dq-review-export-content" style="max-width:420px">
        <div class="dq-review-export-header">
          <span>${t('backupMismatchTitle')}</span>
          <button class="dq-review-close-btn" id="reviewCloseMismatchBtn">×</button>
        </div>
        <div class="dq-review-export-body" style="padding:20px 24px;font-size:14px;line-height:1.8;color:#374151">
          <p style="margin:0 0 12px"><b>${t('backupSource')}</b>${escapeHtml(backupInfo)}</p>
          <p style="margin:0 0 16px"><b>${t('currentPage')}</b>${escapeHtml(currentInfo)}</p>
          <p style="margin:0;color:#6b7280">${t('backupMismatchConfirm')}</p>
        </div>
        <div class="dq-review-export-footer">
          <button class="dq-review-btn dq-review-btn-secondary" id="reviewMismatchCancelBtn">${t('cancel')}</button>
          <button class="dq-review-btn dq-review-btn-primary" id="reviewMismatchConfirmBtn">${t('confirmRestore')}</button>
        </div>
      </div>
    `;

    document.body.appendChild(dialog);

    const closeDialog = () => dialog.remove();

    document.getElementById('reviewCloseMismatchBtn').addEventListener('click', closeDialog);
    document.getElementById('reviewMismatchCancelBtn').addEventListener('click', closeDialog);
    dialog.querySelector('.dq-review-export-overlay').addEventListener('click', closeDialog);

    document.getElementById('reviewMismatchConfirmBtn').addEventListener('click', () => {
      closeDialog();
      onConfirm();
    });
  }

  // ==================== 导出对话框 ====================
  function showExportDialog() {
    if (annotations.length === 0) {
      showToast(t('noCommentsToExport'));
      return;
    }

    const dialog = document.createElement('div');
    dialog.className = 'dq-review-export-dialog';
    dialog.innerHTML = `
      <div class="dq-review-export-overlay"></div>
      <div class="dq-review-export-content">
        <div class="dq-review-export-header">
          <span>${t('exportTitle')}</span>
          <button class="dq-review-close-btn" id="reviewCloseExportBtn">×</button>
        </div>
        <div class="dq-review-export-body" style="display: flex; align-items: center; justify-content: center; min-height: 200px;">
          <div style="text-align: center;">
            <div class="dq-review-loading-spinner"></div>
            <p style="margin-top: 16px; color: #6b7280; font-size: 14px;">${t('generating')}</p>
          </div>
        </div>
      </div>
    `;

    document.body.appendChild(dialog);

    const closeDialog = () => dialog.remove();
    document.getElementById('reviewCloseExportBtn').addEventListener('click', closeDialog);
    dialog.querySelector('.dq-review-export-overlay').addEventListener('click', closeDialog);

    setTimeout(() => {
      const markdown = generateMarkdown();

      dialog.innerHTML = `
        <div class="dq-review-export-overlay"></div>
        <div class="dq-review-export-content">
          <div class="dq-review-export-header">
            <span>${t('exportTitle')}</span>
            <button class="dq-review-close-btn" id="reviewCloseExportBtn">×</button>
          </div>
          <div class="dq-review-export-body">
            <pre id="reviewMarkdownContent">${escapeHtml(markdown)}</pre>
          </div>
          <div class="dq-review-export-footer">
            <button class="dq-review-btn dq-review-btn-secondary" id="reviewCancelExportBtn">${t('cancel')}</button>
            <button class="dq-review-btn dq-review-btn-secondary" id="reviewDownloadMarkdownBtn">${t('downloadFile')}</button>
            <button class="dq-review-btn dq-review-btn-primary" id="reviewCopyMarkdownBtn">${t('copyToClipboard')}</button>
          </div>
        </div>
      `;

      document.getElementById('reviewCloseExportBtn').addEventListener('click', closeDialog);
      document.getElementById('reviewCancelExportBtn').addEventListener('click', closeDialog);
      dialog.querySelector('.dq-review-export-overlay').addEventListener('click', closeDialog);

      document.getElementById('reviewDownloadMarkdownBtn').addEventListener('click', () => {
        downloadMarkdown(markdown);
        showToast(t('fileDownloaded'));
        closeDialog();
      });

      document.getElementById('reviewCopyMarkdownBtn').addEventListener('click', () => {
        copyToClipboard(markdown);
        showToast(t('copiedToClipboard'));
        closeDialog();
      });
    }, 100);
  }

  // ==================== 下载 Markdown 文件 ====================
  function downloadMarkdown(markdown) {
    const today = new Date();
    const year = today.getFullYear();
    const month = String(today.getMonth() + 1).padStart(2, '0');
    const day = String(today.getDate()).padStart(2, '0');
    const dateForFilename = `${year}-${month}-${day}`;
    const pageName = window.location.pathname.split('/').pop().replace('.html', '') || 'prototype';
    const filename = `${pageName}-prototype-review-${dateForFilename}.md`;

    const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.style.display = 'none';

    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  // ==================== 生成 Markdown ====================
  function generateMarkdown() {
    const pageTitle = document.title || t('untitledPage');
    const today = new Date();
    const dateStr = today.toLocaleDateString('zh-CN');
    const year = today.getFullYear();
    const month = String(today.getMonth() + 1).padStart(2, '0');
    const day = String(today.getDate()).padStart(2, '0');
    const dateForFilename = `${year}-${month}-${day}`;

    const pageName = window.location.pathname.split('/').pop().replace('.html', '') || 'prototype';

    const p0 = annotations.filter(a => a.priority === 'P0');
    const p1 = annotations.filter(a => a.priority === 'P1');
    const p2 = annotations.filter(a => a.priority === 'P2');

    // 获取路径：file:// 协议取绝对路径，http(s) 协议取相对路径
    let fullPath = decodeURIComponent(window.location.pathname);
    // file:// 协议下 pathname 就是完整绝对路径
    // http(s) 协议下 pathname 是服务器相对路径（无法获取绝对路径）
    let savePath = '';

    // 提取 HTML 所在目录，拼接 review 文件名
    const dirMatch = fullPath.match(/^(.+)[\/\\][^\/\\]+\.html$/i);
    if (dirMatch) {
      savePath = `${dirMatch[1]}/${pageName}-prototype-review-${dateForFilename}.md`;
    } else {
      savePath = `${pageName}-prototype-review-${dateForFilename}.md`;
    }

    let markdown = `<!--\n`;
    markdown += `${t('savePath')}：${savePath}\n`;
    markdown += `${t('usage')}：${t('usageInstruction')}\n`;
    markdown += `-->\n\n`;

    markdown += `# ${t('reviewRecordTitle')}\n\n`;
    markdown += `> ${t('autoGenerated')}\n\n`;
    markdown += `## ${t('basicInfo')}\n\n`;
    markdown += `- ${t('pageTitle')}：${pageTitle}\n`;
    markdown += `- ${t('reviewDate')}：${dateStr}\n`;
    markdown += `- ${t('totalComments')}：${annotations.length} ${t('commentsCount')}（P0: ${p0.length} / P1: ${p1.length} / P2: ${p2.length}）\n\n`;

    markdown += `## ${t('reviewOpinions')}\n\n`;

    // 生成单条评审记录的 markdown
    function formatAnnotation(a, index) {
      // 获取标注元素的 HTML 开标签
      const elementTag = getElementOpenTag(a);
      markdown += `#### ${index + 1}. [${a.type}]`;
      if (elementTag) {
        markdown += ` \`${elementTag}\``;
      }
      markdown += `\n\n`;
      // 内容：输出全部文本（标题行 + 剩余行）
      markdown += `${a.content.trim()}\n\n`;
    }

    if (p0.length > 0) {
      markdown += `### ${t('p0Must')}\n\n`;
      p0.forEach((a, index) => formatAnnotation(a, index));
    }

    if (p1.length > 0) {
      markdown += `### ${t('p1Should')}\n\n`;
      p1.forEach((a, index) => formatAnnotation(a, index));
    }

    if (p2.length > 0) {
      markdown += `### ${t('p2Optional')}\n\n`;
      p2.forEach((a, index) => formatAnnotation(a, index));
    }

    if (annotations.length === 0) {
      markdown += `${t('noOpinions')}\n`;
    }

    return markdown;
  }

  // ==================== 获取元素开标签 ====================
  // 根据 annotation 的 selector 找到目标元素，提取其开标签（含关键属性）
  function getElementOpenTag(annotation) {
    if (!annotation.selector) return '';
    try {
      const element = findElementSafe(annotation.selector);
      if (!element) return '';

      const tag = element.tagName.toLowerCase();
      // 收集关键属性：class, id, name, type, role, data-* 等
      const attrNames = ['class', 'id', 'name', 'type', 'role', 'placeholder', 'href', 'src'];
      let attrs = '';

      for (const name of attrNames) {
        const val = element.getAttribute(name);
        if (val) {
          // 过滤掉插件自身的 dq-review- 类名
          if (name === 'class') {
            const filtered = val.split(/\s+/)
              .filter(c => c && !c.startsWith('dq-review-'))
              .join(' ');
            if (filtered) {
              attrs += ` class="${filtered}"`;
            }
          } else {
            attrs += ` ${name}="${val}"`;
          }
        }
      }

      // 补充 data-* 属性
      if (element.dataset) {
        for (const [key, val] of Object.entries(element.dataset)) {
          if (val && !key.startsWith('dqReview')) {
            attrs += ` data-${key.replace(/([A-Z])/g, '-$1').toLowerCase()}="${val}"`;
          }
        }
      }

      return `<${tag}${attrs}>`;
    } catch (e) {
      console.warn('[Review Extension V2] getElementOpenTag failed:', e.message);
      return '';
    }
  }

  // ==================== 工具函数 ====================
  function escapeHtml(text) {
    const div = document.createElement('div');
    div.textContent = text;
    return div.innerHTML;
  }

  function copyToClipboard(text) {
    const textarea = document.createElement('textarea');
    textarea.value = text;
    textarea.style.position = 'fixed';
    textarea.style.opacity = '0';
    document.body.appendChild(textarea);
    textarea.select();
    document.execCommand('copy');
    document.body.removeChild(textarea);
  }

  // ==================== Toast 提示 ====================
  function showToast(message) {
    const toast = document.createElement('div');
    toast.className = 'dq-review-toast';
    toast.innerHTML = `
      <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="flex-shrink: 0;">
        <circle cx="12" cy="12" r="10"></circle>
        <line x1="12" y1="8" x2="12" y2="12"></line>
        <line x1="12" y1="16" x2="12.01" y2="16"></line>
      </svg>
      <span>${escapeHtml(message)}</span>
    `;

    document.body.appendChild(toast);

    setTimeout(() => toast.classList.add('show'), 10);

    setTimeout(() => {
      toast.classList.remove('show');
      setTimeout(() => toast.remove(), 300);
    }, 3000);

    toast.addEventListener('click', () => {
      toast.classList.remove('show');
      setTimeout(() => toast.remove(), 300);
    });
  }

  // ==================== 数据持久化 ====================

  // 获取存储键（基于项目名 + 文件名）
  function getStorageKey() {
    const path = window.location.pathname;
    const fileName = path.split('/').pop() || 'index.html';

    // 尝试从路径提取项目名（匹配 /projects/{项目名}/ 模式）
    const projectMatch = path.match(/\/projects\/([^\/]+)\//);
    const projectName = projectMatch ? projectMatch[1] : 'default';

    return `${projectName}_${fileName}`;
  }

  function saveAnnotations() {
    const storageKey = getStorageKey();
    const data = {
      [`annotations_${storageKey}`]: annotations,
      [`currentId_${storageKey}`]: currentAnnotationId
    };

    // 方案 1：同时写入 local 和 sync
    chrome.storage.local.set(data);
    syncToCloud(storageKey);

    console.log(`[Review Extension V2] ${t('savedTo')}: ${storageKey}`);
  }

  // ==================== 方案 1：chrome.storage.sync 云端同步 ====================

  // sync 单个 key 上限 8KB，总量 100KB，需要分片
  function syncToCloud(storageKey) {
    try {
      const dataStr = JSON.stringify({ annotations, currentId: currentAnnotationId });
      const CHUNK_SIZE = 7000; // 留点余量，单 key 上限 8192 字节
      const chunks = [];

      for (let i = 0; i < dataStr.length; i += CHUNK_SIZE) {
        chunks.push(dataStr.substring(i, i + CHUNK_SIZE));
      }

      const syncData = { [`sync_meta_${storageKey}`]: { chunks: chunks.length, timestamp: Date.now() } };
      chunks.forEach((chunk, index) => {
        syncData[`sync_${storageKey}_${index}`] = chunk;
      });

      chrome.storage.sync.set(syncData, () => {
        if (chrome.runtime.lastError) {
          console.warn(`[Review Extension V2] ${t('syncFailed')}:`, chrome.runtime.lastError.message);
        } else {
          console.log(`[Review Extension V2] ${t('syncSaved')} (${chunks.length} chunks)`);
        }
      });
    } catch (e) {
      console.warn('[Review Extension V2] sync error:', e);
    }
  }

  function loadFromSync(storageKey, callback) {
    const metaKey = `sync_meta_${storageKey}`;
    chrome.storage.sync.get(metaKey, (result) => {
      const meta = result[metaKey];
      if (!meta || !meta.chunks) {
        callback(null);
        return;
      }

      const chunkKeys = [];
      for (let i = 0; i < meta.chunks; i++) {
        chunkKeys.push(`sync_${storageKey}_${i}`);
      }

      chrome.storage.sync.get(chunkKeys, (chunkResult) => {
        try {
          let dataStr = '';
          for (let i = 0; i < meta.chunks; i++) {
            dataStr += chunkResult[`sync_${storageKey}_${i}`] || '';
          }
          const data = JSON.parse(dataStr);
          callback(data);
        } catch (e) {
          console.warn('[Review Extension V2] sync parse error:', e);
          callback(null);
        }
      });
    });
  }

  // ==================== 方案 2：每日自动 JSON 备份 ====================


  // ==================== 方案 3：导出嵌入评审数据的 HTML 副本 ====================

  function exportHtmlWithReviews() {
    if (annotations.length === 0) {
      showToast(t('noCommentsToExport'));
      return;
    }

    const reviewData = {
      version: VERSION,
      storageKey: getStorageKey(),
      annotations,
      currentId: currentAnnotationId,
      pageUrl: window.location.href,
      exportDate: new Date().toISOString()
    };

    const dataComment = `<!-- REVIEW_EXTENSION_DATA\n${JSON.stringify(reviewData, null, 2)}\nEND_REVIEW_EXTENSION_DATA -->`;

    // 克隆当前页面 HTML
    const doctype = document.doctype
      ? `<!DOCTYPE ${document.doctype.name}${document.doctype.publicId ? ` PUBLIC "${document.doctype.publicId}"` : ''}${document.doctype.systemId ? ` "${document.doctype.systemId}"` : ''}>`
      : '<!DOCTYPE html>';

    const htmlClone = document.documentElement.cloneNode(true);

    // 移除插件注入的所有 UI 元素
    htmlClone.querySelectorAll('[class^="dq-review"]').forEach(el => el.remove());

    const fullHtml = `${doctype}\n${dataComment}\n${htmlClone.outerHTML}`;

    const blob = new Blob([fullHtml], { type: 'text/html;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const pageName = window.location.pathname.split('/').pop() || 'index.html';
    const today = new Date().toISOString().slice(0, 10);
    const filename = `${pageName.replace('.html', '')}-with-reviews-${today}.html`;

    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.style.display = 'none';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    showToast(t('htmlExported'));
  }

  // ==================== 从 HTML 注释恢复评审数据 ====================

  function loadFromHtmlComments() {
    const html = document.documentElement.outerHTML;
    const match = html.match(/<!-- REVIEW_EXTENSION_DATA\n([\s\S]*?)\nEND_REVIEW_EXTENSION_DATA -->/);
    if (!match) return null;

    try {
      return JSON.parse(match[1]);
    } catch (e) {
      console.warn('[Review Extension V2] HTML comment parse error:', e);
      return null;
    }
  }

  function loadAnnotations() {
    const storageKey = getStorageKey();

    // 优先从 chrome.storage.local 加载
    chrome.storage.local.get([`annotations_${storageKey}`, `currentId_${storageKey}`], (result) => {
      const localAnnotations = result[`annotations_${storageKey}`] || [];
      const localCurrentId = result[`currentId_${storageKey}`] || 0;

      if (localAnnotations.length > 0) {
        // 本地有数据，直接使用
        annotations = localAnnotations;
        currentAnnotationId = localCurrentId;
        console.log(`[Review Extension V2] ${t('loadedFrom')} local: ${annotations.length} ${t('commentsCount')}`);
        return;
      }

      // 本地无数据，尝试从 HTML 注释恢复
      const htmlData = loadFromHtmlComments();
      if (htmlData && htmlData.annotations && htmlData.annotations.length > 0) {
        annotations = htmlData.annotations;
        currentAnnotationId = htmlData.currentId || htmlData.annotations.length;
        saveAnnotations(); // 写回 local
        console.log(`[Review Extension V2] ${t('dataRestoredFromHtml')}: ${annotations.length} ${t('commentsCount')}`);
        showToast(`${t('dataRestoredFromHtml')}（${annotations.length} ${t('commentsCount')}）`);
        return;
      }

      // HTML 也无数据，尝试从 sync 恢复
      loadFromSync(storageKey, (syncData) => {
        if (syncData && syncData.annotations && syncData.annotations.length > 0) {
          annotations = syncData.annotations;
          currentAnnotationId = syncData.currentId || syncData.annotations.length;
          // 写回 local
          chrome.storage.local.set({
            [`annotations_${storageKey}`]: annotations,
            [`currentId_${storageKey}`]: currentAnnotationId
          });
          console.log(`[Review Extension V2] ${t('dataRestoredFromSync')}: ${annotations.length} ${t('commentsCount')}`);
          showToast(`${t('dataRestoredFromSync')}（${annotations.length} ${t('commentsCount')}）`);
        } else {
          console.log(`[Review Extension V2] ${t('loadedFrom')} ${storageKey}: 0 ${t('commentsCount')}`);
        }
      });
    });
  }

  // ==================== 暴露全局接口 ====================
  window.reviewExtension = {
    locateAnnotation,
    deleteAnnotation
  };

  // ==================== 启动 ====================
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }

})();
